-
  #.NET Core config from https://dotnetcore.gaprogman.com/2017/06/08/continuous-integration-and-appveyor/
  configuration: Release
  platform: Any CPU
  deploy:
    - provider: Environment
      name: AllowanceAPI-Production
  image: Visual Studio 2017
  branches:
    only:
    - production
  init:
    # Good practise, because Windows line endings are different from Unix/Linux ones
    - cmd: git config --global core.autocrlf true
  install:
    # Install repo specific stuff here
  before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    # Display minimal restore text
    - cmd: dotnet restore ./BudgetingAPI/BudgetingAPI.csproj --verbosity m
  build_script:
    # output will be in ./src/bin/debug/netcoreapp1.1/publish
    - cmd: dotnet publish ./BudgetingAPI/BudgetingAPI.csproj
  artifacts:
    - path: '\BudgetingAPI\bin\Any CPU\Release\netcoreapp1.1\publish'
      name: BudgetingAPI
      type: WebDeployPackage
